# Generated by Django 2.1.4 on 2018-12-27 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_annotation', '0005_auto_20181227_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='LabeledImage',
        ),
    ]
