# Generated by Django 2.1.4 on 2018-12-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0006_auto_20181227_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeledimage',
            old_name='owner',
            new_name='ownr',
        ),
    ]
