# Generated by Django 2.1.4 on 2018-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0007_auto_20181227_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledimage',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labeledimage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
